### ISSUE TITLE
Command SH raised exception 

### ISSUE THREAD

**Issue by ronaldt80** [Alexwijn/SAT#13]
I just installed your integration, my otgw does not accept the set point command. Is there a minimum firmware version required? Am on 6.1.

 I use a serial connection, can confirm other values are registered, eg. Return water temp.

Also can confirm i removed my other otgw integration to avoid conflict.

```
This error originated from a custom integration.

Logger: pyotgw.pyotgw
Source: custom_components/sat/serial/__init__.py:185
Integration: Smart Autotune Thermostat (documentation, issues)
First occurred: 20:09:44 (4 occurrences)
Last logged: 20:11:25

Command SH with value 55.0 raised exception: Bad Value: The command contained a data value that is not allowed or not supported on this version of the OpenTherm Gateway.
Command SH with value 45.0 raised exception: Bad Value: The command contained a data value that is not allowed or not supported on this version of the OpenTherm Gateway.
```

**Comment by ronaldt80** [comment]
Also some other errors...

```
Logger: pyotgw.commandprocessor
Source: runner.py:188
First occurred: 20:09:44 (36 occurrences)
Last logged: 20:11:25

Unknown message in command queue: PR: Q=P
Command PR failed with PR: Q=P, retrying...
Unknown message in command queue: PR: S=16.00
Command PR failed with PR: S=16.00, retrying...
Command SH failed with SH: BV, retrying..
```.

**Comment by Alexwijn** [comment]
Not sure what you mean with version 6.1, the latest OTGW firmware version is 0.10.2 and SAT is 2.3.2 in beta.

Are you using custom firmware? Can you also tell us SAT version?

**Comment by Alexwijn** [comment]
My apologies, apparently I just learned something too and thought the OTGW-firmware was just an All-In-One firmware, but it was not. I got version 6.0 at the moment, and never updated it. Going to do that now and let you know if I stumble into any issues.

**Comment by ronaldt80** [comment]
Hi, i use develop. Otgw is on serial over tcp/ip through an ethernet component. Bought with nodo shop.

**Comment by Alexwijn** [comment]
The serial integration is a bit deprecated since the MQTT variant has more features. But I just upgraded to 6.5 and everything still works for me, although I do use MQTT. Also note that the Serial integration fully relies on an external package (https://github.com/mvn23/pyotgw), it also hasn't been updated since last. Maybe it broke since 6.1+.

Could you try either? Upgrade to 6.5 and/or try the MQTT integration?

**Comment by ronaldt80** [comment]
The mqqt one only works with an ESP right? Wemos? Or is this also possible with the serial to ethernet connection?

**Comment by Alexwijn** [comment]
I'm not familiar with the Ethernet version, this project heavily relies on the OTGW-firmware (https://github.com/rvdbreemen/OTGW-firmware) for MQTT and the pyotgw package for serial connection.

I'm also not sure why it isn't accepting those setpoints. The only thing I could think of is sending whole numbers instead of ones with decimals.

Did you try the OTGW monitor yet and try to send the same commands?

**Comment by ronaldt80** [comment]
Hi Alex, i have had the thermostat in operation the whole day today and see the set point change so guess it works.

I do see binary_sensor.control_setpoint_synchro at "Detected Problem" continuously (reverting to "Cleared (no problem detected)" two seconds later).

Will try two things coming weekend:
- update firmware
- reinstall integration to setup multi room and detect overshoot protection

Will close this for now. 

In the mean time one observation - the autotune seems a bit too aggressive for my heatpump. Similar to the comment made on the underfloor heating per issue #12  - the setpoint is too high when the error > 0.3; i would expect a more gradual behavior. Eg. Capping the set point based on outside temperature. Ultimately to avoid large swing and ensure the heatpump has a long (low) run as opposed to shorter more frequent runs.
