### ISSUE TITLE
Filtered boiler temperature property in coordinator

### ISSUE THREAD

**Issue by RonnyDeLoor** [Alexwijn/SAT#53]
Hi Alex,
I have been studying your project and 3.0.1 code  with big interest, since I would like to have a sat like thermostat running on ESP32, (esphome).
Although I do not fully understand the magic of the auto tuning yet, I have a question about the filtered boiler temperature used to calculate the derivative part in the PID code.

The coordinator tracks a list of the boiler temperature for the past 60 seconds. The def filtered_boiler_temperature(self) -> float | None: property is not really calculating a filtered boiler temperature, but an average  value of the boiler temperature variation. Usually this is a low positive value.

In the def derivative(self) -> float: property of the pid controller this "filtered" boiler temperature is compared to the output value, usually around the heat curve value I would think.

So my question is, what is the reasoning behind the following part of code to 'kill' the derivative:

        if self._last_boiler_temperature is not None:
            if abs(self._last_error) > 0.1 and abs(self._last_boiler_temperature - output) < 3:
                return 0

            if abs(self._last_error) <= 0.1 and abs(self._last_boiler_temperature - output) < 7:
                return 0

I can see some logic when the last_boiler_temperature would be a noise filtered value of the boiler temperatures (as the comment is telling me). But to my understanding filtered_boiler-temperature is not returning that.

Sincerely,
Ronny

**Comment by sergeantd83** [comment]
Hi Ronny,

I requested this change way long time ago. It is a "leftover" code that needs to be removed, since there is no real purpose of being there. I am impressed that you found such a small detail in the code!
Actually we need the boiler flow water temperature when we calculate the duty cycle ON/OFF times. Constantly monitoring the boiler temperature, SAT is able to adapt is strategy on every heating system ( Boiler, pipes, radiators ) and eliminate short cycling.

**Comment by RonnyDeLoor** [comment]
Hi,

Well, as I said, I consider building an esp32 (ESPHOME) sat thermostat external component. I am not comfortable with the concept of controlling the boiler over a wifi network link. I already have the opentherm communication running in ESPHOME. So I could write a homeassistant class to replace the OT gateway, the opentherm component will soon be part of the official release.

ESPHOME external components are developed in c++, there is no 'coroutine' functionality. To make it work I must split up the SAT code in multiple components. Each of the components loop() or update() components run in the ESP32 main loop, and so seem to run in 'parallel'. That is why I studied the SAT code in such detail. Being recently retired, I have plenty of time to keep my mind creative ... As they say, retired persons do not have free time )-;

By the way, I think I found another one. The heating curve autotune is calculating an optimal coefficient, but where does it get active ? The autotune routine is called when the PID controller is in the dead band, but I do not find any reference where the optimal coefficient replaces the initial coefficient ...

My heating system is a mixed radiator / floor heating system. The main thermostat controls the floor heating. The boiler feed temperature is mixed with floor return water using a 3way valve, so the boiler can supply hotter water for the radiators (if there is demand) and the 3way valve mixes it down to the required floor feed temperature. 

So I am trying to work out how to implement this.

Control the 3way mixing valve with a floor heating curve and  always control the boiler temperature with a radiator heating curve? That makes the boiler run at about 7 degrees higher than the floor feed temperature, the 3way valve will take care of
supplying the lower floor feed temperature.

What if no radiator demand? The 3way mixing valve likes to mix down, so input boiler feed temperature should always be higher than the floor feed temperature.

I have seen that in case of my Itho Daalderop Cube Duo boiler, the boiler temperature goes way high when the boiler is supplying hot water, the boiler temperature only reflects the heating feed temperature when the heating is on. This makes the PWM hopping around in the PWM off state. Fortunately the Cube Duo has another sensor on the 'floor feed output', this one is behaving somewhat nicer, but to some extend the temperature value rising when there is no flow.

As you see, I have fun with this great project!

Sincerely,
Ronny

**Comment by sergeantd83** [comment]
> Well, as I said, I consider building an esp32 (ESPHOME) sat thermostat external component. I am not comfortable with the concept of controlling the boiler over a wifi network link. I already have the opentherm communication running in ESPHOME. So I could write a homeassistant class to replace the OT gateway, the opentherm component will soon be part of the official release.

We don't think that building a thermostat like SAT fits within an ESPHome project. Home Assistant is the perfect place to manage all the multi-room climate entities and perform the necessary calculations in one centralized and well-organized location. How can one or more TRV climate entities only be exposed in ESPHome? It is not possible. SAT wouldn't be able to know what's really happening in the system (for example, all TRVs might be closed), making SAT a dangerous controller. Many projects try to manage the boiler without fully understanding the system's status, but SAT will never do this to any user. If SAT were to become an ESPHome custom component, it would be risky. We have worked really hard to bring SAT to such a high level and overcome all kinds of issues.

Instead of attempting to create an ESPHome custom component, we suggest simply adding a backup thermostat to ensure SAT continues to work as designed in case Home Assistant fails for any reason.

I'm impressed by your methodology in understanding the code, and I'm confident that you'll help SAT in the future. 

>By the way, I think I found another one. The heating curve autotune is calculating an optimal coefficient, but where does it get active ? The autotune routine is called when the PID controller is in the dead band, but I do not find any reference where the optimal coefficient replaces the initial coefficient ...

Oh, you found another unfinished development. Someday, it will become a fuzzy tuner.

**Comment by RonnyDeLoor** [comment]
Thank you for sharing your opinion on SAT and ESPHome. I agree that in case of multi-rooms systems, Home Assistant is the right place to have a total overview. In fact I was considering to use Home Assistant on the input end, gathering and combining sensor data from several bluetooth thermometers in the house, alternative is using Zigbee sensors connected to HA.

I also appreciate your hard work to bringing SAT to this high level, and I enjoyed analyzing your novel approach. As far as I have seen, SAT is more or less the only serious approach to build a 'smart' or 'self adjusting' thermostat. I do not consider a thermostat than I can read or control from my phone to be 'smart'. ;-) I just did not expect unfinished developments / experiment leftovers in 'released' code. Anyway, thanks for sharing your work on an open source platform.

My system does have the old thermostats with on/off relay contacts. On for the floor heating on the Cube duo LT circuit, and one for the radiators on the HT circuit, but the Cube duo has the possibility to control the LT circuit using opentherm. So I started with simple ESPHome thermostat + opentherm interface on ESP32 board. Now I want something better ...

To be continued ...
