### ISSUE TITLE
Custom setup output to input_number helper

### ISSUE THREAD

**Issue by andreid1303** [Alexwijn/SAT#54]

**Comment by andreid1303** [comment]
I would like to use SAT integration for controlling boiler flow temp via Ebus. For this setup I only need output to custom input_number helper and using custom sensors in HA. Is it possible?
It seems simple: no MQTT initialisation, just pass calculations to that number if provided via setup options.

**Comment by sergeantd83** [comment]
SAT is not using this simplistic logic. Multiple algorithms are working at the same time in order to bring the best user experience in comfort, energy savings and increase the life time of the boiler. As far as I know, the author of the [EMS-ESP32](https://github.com/emsesp/EMS-ESP32) project is working to bring native support to SAT. So stay tuned!

**Comment by andreid1303** [comment]
That what I was looking for: autotune heating curve and pid coefficients with your multiple algorithms.
But I have Vaillant Atmo gas boiller, it is not Opentherm compatible. But I can set target FlowTemp with HA automations using using Ebus daemon. The idea is to setup a dump Opentherm MQTT and use thermostat output as set point. Will this work?

**Comment by andreid1303** [comment]
I have install SAT integration and see that there is Simulated Gateway option. Will try it.

**Comment by Alexwijn** [comment]
Do note that the Simulated Gateway is just for development purposes, it's not supposed to be used in production. It's probably gets removed at some point.
